AWSTemplateFormatVersion: '2010-09-09'
Description: 'BOM-driven Compute Infrastructure - EC2 Instances'

Parameters:
  Environment:
    Type: String
    Default: production
    Description: Environment name for resource tagging
  
  NetworkStackName:
    Type: String
    Default: network-stack
    Description: Name of the network stack to import VPC resources
  
  InstanceType1:
    Type: String
    Default: t3.medium
    Description: EC2 instance type for web server 1
  
  InstanceType2:
    Type: String
    Default: t3.medium
    Description: EC2 instance type for web server 2
  
  VolumeSize1:
    Type: Number
    Default: 40
    Description: EBS volume size in GB for web server 1
  
  VolumeSize2:
    Type: Number
    Default: 40
    Description: EBS volume size in GB for web server 2
  
  CreateInstance1:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Whether to create web server 1
  
  CreateInstance2:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    Description: Whether to create web server 2
  
  KeyPairName:
    Type: String
    Default: ''
    Description: EC2 Key Pair name for SSH access (optional)

Conditions:
  CreateWebServer1: !Equals [!Ref CreateInstance1, 'true']
  CreateWebServer2: !Equals [!Ref CreateInstance2, 'true']
  HasKeyPair: !Not [!Equals [!Ref KeyPairName, '']]

Mappings:
  RegionMap:
    eu-north-1:
      AMI: ami-0014ce3e52359afbd  # Amazon Linux 2023 AMI
    us-east-1:
      AMI: ami-0c02fb55956c7d316  # Amazon Linux 2023 AMI
    us-west-2:
      AMI: ami-0c2d3e23d757c2917  # Amazon Linux 2023 AMI

Resources:
  # IAM Role for EC2 instances
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'BOM-EC2-Role-${Environment}-${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: BOM-Infrastructure

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub 'BOM-EC2-Profile-${Environment}-${AWS::StackName}'
      Roles:
        - !Ref EC2InstanceRole

  # Security Group for Web Servers
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for BOM web servers
      VpcId:
        Fn::ImportValue: !Sub '${NetworkStackName}-${Environment}-VpcId'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP access
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS access
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp:
            Fn::ImportValue: !Sub '${NetworkStackName}-${Environment}-VpcCidr'
          Description: SSH access from VPC
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: All outbound traffic
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-web-server-sg'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: BOM-Infrastructure

  # Web Server 1
  WebServer1:
    Type: AWS::EC2::Instance
    Condition: CreateWebServer1
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      InstanceType: !Ref InstanceType1
      KeyName: !If [HasKeyPair, !Ref KeyPairName, !Ref 'AWS::NoValue']
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      SubnetId:
        Fn::ImportValue: !Sub '${NetworkStackName}-${Environment}-PublicSubnet1aId'
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp3
            VolumeSize: !Ref VolumeSize1
            DeleteOnTermination: true
            Encrypted: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          
          # Install CloudWatch agent
          yum install -y amazon-cloudwatch-agent
          
          # Create simple web page
          cat > /var/www/html/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
              <title>BOM Web Server 1</title>
          </head>
          <body>
              <h1>Welcome to BOM Infrastructure</h1>
              <p>Web Server 1 - ${Environment} Environment</p>
              <p>Instance ID: $(curl -s http://169.254.169.254/latest/meta-data/instance-id)</p>
              <p>Availability Zone: $(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)</p>
          </body>
          </html>
          EOF
          
          # Install SSM agent (already included in Amazon Linux 2023)
          systemctl start amazon-ssm-agent
          systemctl enable amazon-ssm-agent
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-web-server-1'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: BOM-Infrastructure
        - Key: Role
          Value: WebServer

  # Web Server 2 (conditional)
  WebServer2:
    Type: AWS::EC2::Instance
    Condition: CreateWebServer2
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      InstanceType: !Ref InstanceType2
      KeyName: !If [HasKeyPair, !Ref KeyPairName, !Ref 'AWS::NoValue']
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      SubnetId:
        Fn::ImportValue: !Sub '${NetworkStackName}-${Environment}-PublicSubnet1bId'
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp3
            VolumeSize: !Ref VolumeSize2
            DeleteOnTermination: true
            Encrypted: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          
          # Install CloudWatch agent
          yum install -y amazon-cloudwatch-agent
          
          # Create simple web page
          cat > /var/www/html/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
              <title>BOM Web Server 2</title>
          </head>
          <body>
              <h1>Welcome to BOM Infrastructure</h1>
              <p>Web Server 2 - ${Environment} Environment</p>
              <p>Instance ID: $(curl -s http://169.254.169.254/latest/meta-data/instance-id)</p>
              <p>Availability Zone: $(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)</p>
          </body>
          </html>
          EOF
          
          # Install SSM agent (already included in Amazon Linux 2023)
          systemctl start amazon-ssm-agent
          systemctl enable amazon-ssm-agent
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-web-server-2'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: BOM-Infrastructure
        - Key: Role
          Value: WebServer

Outputs:
  WebServer1Id:
    Description: Web Server 1 Instance ID
    Value: !If [CreateWebServer1, !Ref WebServer1, 'Not Created']
    Export:
      Name: !Sub '${AWS::StackName}-WebServer1Id'

  WebServer1PublicIP:
    Description: Web Server 1 Public IP
    Value: !If [CreateWebServer1, !GetAtt WebServer1.PublicIp, 'Not Created']
    Export:
      Name: !Sub '${AWS::StackName}-WebServer1PublicIP'

  WebServer1PrivateIP:
    Description: Web Server 1 Private IP
    Value: !If [CreateWebServer1, !GetAtt WebServer1.PrivateIp, 'Not Created']
    Export:
      Name: !Sub '${AWS::StackName}-WebServer1PrivateIP'

  WebServer2Id:
    Description: Web Server 2 Instance ID
    Value: !If [CreateWebServer2, !Ref WebServer2, 'Not Created']
    Export:
      Name: !Sub '${AWS::StackName}-WebServer2Id'

  WebServer2PublicIP:
    Description: Web Server 2 Public IP
    Value: !If [CreateWebServer2, !GetAtt WebServer2.PublicIp, 'Not Created']
    Export:
      Name: !Sub '${AWS::StackName}-WebServer2PublicIP'

  WebServer2PrivateIP:
    Description: Web Server 2 Private IP
    Value: !If [CreateWebServer2, !GetAtt WebServer2.PrivateIp, 'Not Created']
    Export:
      Name: !Sub '${AWS::StackName}-WebServer2PrivateIP'

  WebServerSecurityGroupId:
    Description: Web Server Security Group ID
    Value: !Ref WebServerSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-WebServerSecurityGroupId'

  EC2RoleArn:
    Description: EC2 Instance Role ARN
    Value: !GetAtt EC2InstanceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-EC2RoleArn'