AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple Storage Stack for BOM Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: development
  
  CreateBucket:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
  
  BucketName:
    Type: String
    Default: ''

Conditions:
  CreateS3Bucket: !Equals [!Ref CreateBucket, 'true']
  HasBucketName: !Not [!Equals [!Ref BucketName, '']]

Resources:
  AppStorageBucket:
    Type: AWS::S3::Bucket
    Condition: CreateS3Bucket
    Properties:
      BucketName: !If 
        - HasBucketName
        - !Ref BucketName
        - !Sub 'bom-storage-${Environment}-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-app-storage'

Outputs:
  BucketName:
    Description: S3 Bucket Name
    Value: !If [CreateS3Bucket, !Ref AppStorageBucket, 'Not Created']
  
  BucketArn:
    Description: S3 Bucket ARN
    Value: !If [CreateS3Bucket, !GetAtt AppStorageBucket.Arn, 'Not Created']