AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple Storage Stack for BOM Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: development
  
  CreateBucket:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
  
  BucketName:
    Type: String
    Default: ''
  
  EnableVersioning:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
  
  EnableEncryption:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']

Conditions:
  CreateS3Bucket: !Equals [!Ref CreateBucket, 'true']
  HasBucketName: !Not [!Equals [!Ref BucketName, '']]
  EnableS3Versioning: !Equals [!Ref EnableVersioning, 'true']
  EnableS3Encryption: !Equals [!Ref EnableEncryption, 'true']

Resources:
  AppStorageBucket:
    Type: AWS::S3::Bucket
    Condition: CreateS3Bucket
    Properties:
      BucketName: !If 
        - HasBucketName
        - !Ref BucketName
        - !Sub 'bom-storage-${Environment}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: !If [EnableS3Versioning, Enabled, Suspended]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-app-storage'
        - Key: Project
          Value: BOMInfrastructure
        - Key: Environment
          Value: !Ref Environment

Outputs:
  BucketName:
    Description: S3 Bucket Name
    Value: !If [CreateS3Bucket, !Ref AppStorageBucket, 'Not Created']
  
  BucketArn:
    Description: S3 Bucket ARN
    Value: !If [CreateS3Bucket, !GetAtt AppStorageBucket.Arn, 'Not Created']