AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM OIDC Role for GitHub Actions BOM-driven CloudFormation deployments'

Parameters:
  GitHubRepository:
    Type: String
    Default: 'your-org/aws-bom-infrastructure'
    Description: 'GitHub repository in format owner/repo-name'
  
  GitHubBranch:
    Type: String
    Default: 'main'
    Description: 'GitHub branch allowed to assume this role'

Resources:
  # OIDC Identity Provider for GitHub Actions
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCIdentityProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd

  # IAM Role for GitHub Actions
  GitHubActionsBOMCloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubActionsBOMCloudFormationRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
              StringLike:
                'token.actions.githubusercontent.com:sub': !Sub 'repo:${GitHubRepository}:ref:refs/heads/${GitHubBranch}'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
      Policies:
        - PolicyName: BOMCloudFormationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # CloudFormation permissions
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: '*'
              
              # IAM permissions for CloudFormation service role
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:PassRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:GetRolePolicy
                  - iam:CreateInstanceProfile
                  - iam:DeleteInstanceProfile
                  - iam:AddRoleToInstanceProfile
                  - iam:RemoveRoleFromInstanceProfile
                Resource: 
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/BOM-*'
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:instance-profile/BOM-*'
              
              # EC2 and VPC permissions
              - Effect: Allow
                Action:
                  - ec2:*
                Resource: '*'
              
              # S3 permissions
              - Effect: Allow
                Action:
                  - s3:*
                Resource: '*'
              
              # RDS permissions
              - Effect: Allow
                Action:
                  - rds:*
                Resource: '*'
              
              # Application Load Balancer permissions
              - Effect: Allow
                Action:
                  - elasticloadbalancing:*
                Resource: '*'
              
              # Systems Manager permissions (for parameter store)
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:PutParameter
                  - ssm:DeleteParameter
                Resource: !Sub 'arn:aws:ssm:*:${AWS::AccountId}:parameter/BOM/*'
              
              # CloudWatch Logs permissions
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Resource: '*'

      Tags:
        - Key: Project
          Value: BOM-Infrastructure
        - Key: Purpose
          Value: GitHub-Actions-OIDC
        - Key: Environment
          Value: Production

Outputs:
  RoleArn:
    Description: 'ARN of the GitHub Actions OIDC Role'
    Value: !GetAtt GitHubActionsBOMCloudFormationRole.Arn
    Export:
      Name: GitHubActionsBOMCloudFormationRoleArn
  
  RoleName:
    Description: 'Name of the GitHub Actions OIDC Role'
    Value: !Ref GitHubActionsBOMCloudFormationRole
    Export:
      Name: GitHubActionsBOMCloudFormationRoleName